# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YingKe_OC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YingKe_OC
pod 'AFNetworking', '~> 3.2.0'
pod 'SDWebImage', '~> 4.3.3'
pod 'Masonry', '~> 1.1.0'
pod 'YYKit', '~> 1.0.9'

pod 'MJExtension', '~> 3.0.13'
pod 'LFLiveKit', '~> 2.6'
end
